/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './hooks/**/*.{js,jsx}',
    './lib/**/*.{js,jsx}',
    './stores/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--canvas)',
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        surfaceSoft: 'var(--surface-soft)',
        surfaceHover: 'var(--surface-hover)',
        fg: 'var(--fg)',
        fgMuted: 'var(--fg-muted)',
        muted: 'var(--muted)',
        subtle: 'var(--subtle)',
        border: 'var(--border)',
        borderStrong: 'var(--border-strong)',
        divider: 'var(--divider)',
        accent: 'var(--accent)',
        accentHover: 'var(--accent-hover)',
        accentSoft: 'var(--accent-soft)',
        accentContrast: 'var(--accent-contrast)',
        danger: 'var(--danger)',
        dangerSoft: 'var(--danger-soft)',
        warning: 'var(--warning)',
        warningSoft: 'var(--warning-soft)',
        success: 'var(--success)',
        successSoft: 'var(--success-soft)',
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '16px', letterSpacing: '0.01em' }],
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '20px' }],
        base: ['14px', { lineHeight: '22px' }],
        md: ['15px', { lineHeight: '24px' }],
        lg: ['16px', { lineHeight: '26px' }],
        xl: ['18px', { lineHeight: '28px' }],
        '2xl': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em' }],
        '3xl': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em' }],
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '10px',
        '2xl': '12px',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        card: 'var(--shadow-md)',
        popover: 'var(--shadow-popover)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
