export const ROLES = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
};

export const GOAL_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED',
};

export const ACTION_STATUS = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
};

export const PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const NOTIFICATION_TYPE = {
  MENTION: 'MENTION',
  ASSIGNED_ACTION_ITEM: 'ASSIGNED_ACTION_ITEM',
  INVITED_TO_WORKSPACE: 'INVITED_TO_WORKSPACE',
};
